package br.com.mascenadev.screanmatchfrases.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * @author Gilberto Dev
 * @version 1.0.0
 * @since 2025-06-14
 * <p>
 * This configuration class sets up the OpenAPI (Swagger) documentation for the Screanmatch-Phrases API.
 * It defines the metadata for the API documentation, such as title, version, description, and licensing information.
 *
 * <p>
 * This setup ensures that your API's endpoints, models, and operations are properly documented
 * and accessible via the Swagger UI, facilitating easy testing and understanding for consumers
 * and other developers.
 * </p>
 */
@Configuration
public class SwaggerConfig {

    /**
     * Injects the API version from the application's properties file (e.g., application.properties or application.yml).
     * The value is retrieved from the property `screanmatch-phrases.api.version`.
     */
    @Value("${screanmatch-phrases.api.version}")
    private String apiVersion;

    /**
     * Configures and provides a custom {@link OpenAPI} bean for the Spring context.
     * This method defines the core information displayed in the Swagger UI.
     *
     * <p>
     * It sets the API's title, dynamically injects the version, provides a description,
     * and links to the licensing information generated by {@link #apiLicense()}.
     * </p>
     *
     * @return An {@link OpenAPI} object containing the API's documentation metadata.
     */
    @Bean
    public OpenAPI customOpenAPI() {
        return new OpenAPI().info(
                new Info()
                        .title("Screanmatch-Phrases API")
                        .version(apiVersion)
                        .description("Documentation of Screanmatch-Phrases API")
                        .license(apiLicense()));

    }

    public License apiLicense() {
        return new License()
                .name("MIT License")
                .url("https://github.com/Gilberto-Mascena/screanmatch-frases-api/blob/main/LICENSE.md");
    }
}
